name: Auto Pull

on:
  push:
    branches:
      - prod_branch

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Server & Run Commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-13-49-21-198.eu-north-1.compute.amazonaws.com 
          cd INT_analytics_app 
          git pull origin prod_branch
          pip install -r requirements.txt          
          sudo systemctl restart flaskapp
          
          
          
