name: Auto Pull

on:
  push:
    branches:
      - prod_branch

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to bare repository
        run: |
          echo "git pull"
